### ISSUE TITLE
Provide wheel distribution on PyPI

### ISSUE THREAD

**Issue by edmorley** [graphql-python/graphql-relay-py#10]
Hi!

Please could this package also by made available as a wheel on PyPI?
https://pypi.python.org/pypi/graphql-relay/0.4.5

Wheels have the following advantages:
* Faster installation time
* Allows the wheel cache to work even when using the new pip hash-checking mode
* Allows tools to statically inspect the package metadata without having to execute untrusted code.
* ...and more - see: http://pythonwheels.com

This package is pure Python and supports both Python 2 and 3, so can be distributed as a "universal wheel":
https://packaging.python.org/tutorials/distributing-packages/#wheels

To save having to pass `--universal` to `setup.py` each time, the pref can be saved in `setup.cfg`:

```
[bdist_wheel]
universal=1
```

The Python packaging guide recommends using [Twine](https://github.com/pypa/twine) to upload packages:
https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

So with the `setup.cfg` as above, the steps for building/uploading a new release are then:

```bash
$ pip install -U twine setuptools wheel
$ rm -rf dist/ build/
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

The PyPI package listing will then display two entries for the new release, one with type "Source" and the other "Python Wheel".

Many thanks :-)

**Comment by edmorley** [comment]
I'm happy to open a PR for this, but would you prefer:
1) A new section in the README with publishing steps
2) A PyPI deploy entry in .travis.yml, similar to what graphene-django does ([here](https://github.com/graphql-python/graphene-django/blob/cec1a8448048ce55a2844df63b295b8d9d5000d7/.travis.yml#L60-L66))
3) A setup.py `publish` command (similar to what a few other packages do)
4) Just the `setup.cfg` universal wheel entry, and the rest left as something for maintainers to remember whenever they perform a new release

Cheers :-)

**Comment by syrusakbary** [comment]
2 and 4 should be enough :)
(If you wanna still work on 1 and 3 I will still merge!)

**Comment by Cito** [comment]
The last version in all three branches v0.5.0, v2.0.1, v3.0.0 are now available as wheels, and future versions will be automatically deployed as wheels, too.
