### ISSUE TITLE
Incompatibility with new graphql-core resolvers API

### ISSUE THREAD

**Issue by messa** [graphql-python/graphql-relay-py#17]
Hi! The tests are now failing - see a Travis build from my just-forked repository: https://travis-ci.org/messa/graphql-relay-py/builds/485088298

```
GraphQLLocatedError("<lambda>() got an unexpected keyword argument 'first'",)
```

I think the major cause of the errors is the API change in [graphql-core v2.0.0](https://github.com/graphql-python/graphql-core/releases/tag/v2.0.0):

> New resolvers API. Moving from resolver(root, args, context, info) to resolver(root, info, **args)

It would be possible to limit versions of the graphql-core depency below 2.0.0 (it's now `'graphql-core>=0.5.0'`), but I think that would be not very nice.

Would you accept a pull request that updates the code to the new resolver API?

**Comment by Cito** [comment]
This has been fixed in v2.0, so this issue can be closed.
