### ISSUE TITLE
Release notes needed (dependencies breaking snapshots)

### ISSUE THREAD

**Issue by tony** [graphql-python/graphql-relay-py#26]
Related: #15 

Graphene's 2.1.7 release on July 15th bumped graphql-relay 0.4.5 to 2.0.

https://pypi.org/project/graphene/#history

This is a patch-release that breaks `SnapshotTest` (mentioned in graphene's documentation: https://docs.graphene-python.org/en/latest/testing/)

It's not clear what the changes / ramifications / intentions of 0.4.x -> 2.x of relay are. What's necessary in graphene 2.1.7 that https://github.com/graphql-python/graphene/pull/1032 fixed.

**Comment by Cito** [comment]
We're trying to consolidate version numbers throughout the whole Graphene ecosystem while progressing towards graphql-core 3, after Graphene development has been in hiatus for a long time. 

* graphql-relay < 2: Supports Graphene < 2
* graphql-relay 2.x: Supports Graphene 2.x
* graphql-relay 3.x: Supports Graphene 3.x

That's why this change was necessary.

Is there a concrete action item for graphql-relay-py that should be handled in this issue? Please help us by submitting very specific issues and PRs. These projects are currently maintained by various volunteers in their spare time. Any help is welcome.

**Comment by tony** [comment]
@Cito I don't want to hold up the flow. No one else except me has mentioned anything

Is there _already_ a release notes / CHANGES for graphql-relay-python and I'm just not seeing it? If so my mistake.

> Is there a concrete action item for graphql-relay-py that should be handled in this issue? 


1. I think there should be a `CHANGES` file of what happened between versions. Whether or not it'd break compatibility, API changes, behavior changes. Also, the why's, such as compatibility between graphql are worth mentioning here.
2. Add the changes to the release notes at https://github.com/graphql-python/graphql-relay-py/releases
3. It'd be worth adding the graphql-relay compatibility to the README

>  Please help us by submitting very specific issues and PRs. 

Hm. I think changelogs are best described by the authors that cut the release. _Normally_ it's best to do it when it happens so it's fresh on the mind.

I'd like to, but going back into change logs to get the gist of what is happening is hard to backtrack, let alone staying correct in the process. Does that make sense? I don't have a lot of familiarity with the history of this projects and others. That's a different thing to ask than fixing something `master` since it involves digging into motivations of past changes.

> These projects are currently maintained by various volunteers in their spare time. Any help is welcome.

Yes, I may be proposing PR's to projects in this org, I'm trying to catch up since there's a lot of action. And thanks for your contributions @Cito as well as all other contributors @syrusakbary @jkimbo @mvanlonden @jhgg @pmlandwehr!

**Comment by Cito** [comment]
You're right, creating a changelog is best done by the maintainers. This little library is normally not used directly, only by upstream projects, but yes, that's no excuse.

Will keep this open to remind myself to

- [ ] Update and improve the README
- [ ] Add a CHANGELOG and GitHub release
