### ISSUE TITLE
Incude tests in Python package?

### ISSUE THREAD

**Issue by crazyscientist** [graphql-python/graphql-relay-py#28]
Hi there,

I'm building an RPM package for `graphql-relay` at https://build.opensuse.org, but it would be great, if the unittests were part of the actual Python package on PyPI, so that I could run them after the build process to verify the correct installation.

Would you mind including them in the next release?

**Comment by Cito** [comment]
Seems they are in fact missing in the source distribution and I agree they should be put in there. Is this what you are talking about? They should not be installed or included in binary packages, though.

**Comment by crazyscientist** [comment]
> Is this what you are talking about?

Yes, that is what I meant.  I'm sorry for my inaccurate description.

**Comment by Cito** [comment]
Ok, v2.0.1 has now been released on PyPI including the tests.
