### ISSUE TITLE
PEP8 issues

### ISSUE THREAD

**Issue by rapilabs** [graphql-python/graphql-relay-py#3]
Running flake8 on the source reveals a variety of issues.

More importantly though is the JavaScript naming convention being used (not reported by flake8).  Please use the recommended naming convention as specified in PEP8.

**Comment by syrusakbary** [comment]
Hi @rapilabs, thanks for pointing this out.
I will make the syntax flake8-compatible and also will improve the naming for functions/vars to be more Pythonic.
However I do not have right now a lot of time as I'm working in [Graphene](https://github.com/syrusakbary/graphene), so don't know yet when I will have time.

Feel free to fix flake8 tests (or the function naming!) if you would like to... any pull requests are welcome!
