### ISSUE TITLE
Incorrect Optional typing on PageInfo hasPreviousPage and hasNextPage

### ISSUE THREAD

**Issue by markedwards** [graphql-python/graphql-relay-py#30]
The typing of `PageInfo.hasPreviousPage` and `PageInfo.hasNextPage` appears to be incorrectly indicated as `Optional[bool]` [here](https://github.com/graphql-python/graphql-relay-py/blob/ac5f88848fcad631034c4e54eba0bb7970e8b993/src/graphql_relay/connection/connectiontypes.py#L15-L16).

Is there a reason for this, or can it be fixed?

**Comment by Cito** [comment]
The reason is that relay-py is a direct port of relay-js which defines them as optional. I have now asked whether it can be fixed [there](https://github.com/graphql/graphql-relay-js/issues/243), then we can port it back here.

**Comment by markedwards** [comment]
Thanks @Cito.

**Comment by Cito** [comment]
This has now been fixed upstream and here (to be released).
