### ISSUE TITLE
Six package dependencies incompatible with awsebcli

### ISSUE THREAD

**Issue by ckristhoff** [graphql-python/graphql-relay-py#34]
Hello

I'm trying to use awsebcli to deploy my web application to AWS. When I try to install awsebcli I get next error:

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches six<1.12.0,<2,>=1.10.0,>=1.11.0,>=1.12,>=1.3.0,>=1.4.0,>=1.5,>=1.9.0
Tried: 0.9.0, 0.9.1, 0.9.2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.0, 1.5.1, 1.5.1, 1.5.2, 1.5.2, 1.6.0, 1.6.0, 1.6.1, 1.6.1, 1.7.0, 1.7.0, 1.7.1, 1.7.1, 1.7.2, 1.7.2, 1.7.3, 1.7.3, 1.8.0, 1.8.0, 1.9.0, 1.9.0, 1.10.0, 1.10.0, 1.11.0, 1.11.0, 1.12.0, 1.12.0, 1.13.0, 1.13.0, 1.14.0, 1.14.0, 1.15.0, 1.15.0
Skipped pre-versions: 1.0b1
There are incompatible versions in the resolved dependencies.

I'm using pipenv. graphql-relay-py requires six>=1.12 and awsebcli requires >=1.11.0,<1.12.0

is there any way to resolve this dependency?

**Comment by Cito** [comment]
The current vresion of graphql-relay-py does not require six any more.
