### ISSUE TITLE
from_global_id() differs from reference implementation

### ISSUE THREAD

**Issue by markedwards** [graphql-python/graphql-relay-py#39]
The python `from_global_id` does not exhibit the same behavior as the reference TypeScript implementation when handling invalid input.

Examples:
* `from_global_id("invalid")` raises `binascii.Error`
* `from_global_id("")` raises `TypeError`
* `from_global_id(b64encode(b"foo"))` raises `TypeError`

In the first two cases, the reference implementation returns `{type: "", id: ""}`.  In the third case, it returns `{type: "", id: "foo"}`.  In no case does it throw an error.

This might seem like nitpicking, but it can cause significant differences in how user input ends up being handled.

**Comment by Cito** [comment]
Thanks for reporting. We are still lagging behind relay-js which switched to a custom base64 implementation in version 0.8 to make the behavior more predictable on different platforms. I'm currently trying to bring relay-py in line with the current version of relay-js and will then probably use the same implementation so that we will be fully compatible again.

**Comment by markedwards** [comment]
Yeah, I agree that porting the relay-js implementation is the right plan.  If I get time I will try to contribute here.

**Comment by Cito** [comment]
The main problem is that we currently cannot release because travis-ci.org stopped working. We need the project owner on PyPI @syrusakbary so we can repair this, I already contacted him.

**Comment by Cito** [comment]
Ok, @syrusakbary already responded, will work on it this week.

**Comment by markedwards** [comment]
Great.  Since you are able to contact him, can you ask him to unbreak aiodataloader?  People are getting exasperated:
https://github.com/syrusakbary/aiodataloader/issues/16

**Comment by Cito** [comment]
This should be solved in v3.1.3 now. Please reopen if there are still any differences.
