### ISSUE TITLE
Return a tuple instead of ResolvedGlobalId

### ISSUE THREAD

**Issue by shangxiao** [graphql-python/graphql-relay-py#4]
I think we can remove the need for a class to hold return values given that we now are dealing with Python and have the ability to unpack.  I'm also not entirely sure why it was in the js lib as es6 has unpacking ("destructuring").

**Comment by syrusakbary** [comment]
You're right. Probably we can avoid this class ;)

**Comment by miracle2k** [comment]
I miss it. 

``from_global_id(foo).id`` is just more clear than ``from_global_id(foo)[1]``

**Comment by miracle2k** [comment]
FWIW, was removed in https://github.com/graphql-python/graphql-relay-py/commit/ad6cb9054ada58786e64c63fa7e3f83ac1e1998b
