### ISSUE TITLE
Breaking change introduced with a patch by changing module names

### ISSUE THREAD

**Issue by vladr11** [graphql-python/graphql-relay-py#44]
### Problem

There has been introduced a breaking change since the version `3.1.1`. Namely, the modules have been renamed to follow the snake_case naming convention in the commit [f15bbb](https://github.com/graphql-python/graphql-relay-py/commit/f15bbb99b92ec59d4ca7dc97e4c0dd6ad4bdcdc5#diff-3c7192841e5c8941eb90114b820df7688aa569a1da2e8d855cbe6a5d777b3a60).

This causes some runtime (import) errors after installing/updating dependencies:

```
ModuleNotFoundError: No module named 'graphql_relay.connection.arrayconnection'
```

in on of the 3rd parties that use this library.

Yes, it uses `from graphql_relay.connection.arrayconnection import ...` instead of `from graphql_relay import ...`.

I have been able to fix this issue by adding `graphql-relay` as a project dependency and pinning the version to `3.1.0`, but this is not the desired solution, as we do not use the library directly in the project.

### Proposed resolution:

One solution would be to allow the old modules reside in the project and mark them as deprecated. Their sole purpose would be to import the contents of the renamed files and allow them to be imported using the old module name.

I can create a Pull request with this patch if this is approved, or with any other proposed solution.

**Comment by Cito** [comment]
Sorry. This would not be a breaking change if the documentation had explained properly that functions should always be imported from the top level. I have now added a note about this in the README file.

If you want to provide a PR that would be helpful. I think a `from .foo import *` would suffice, and maybe also output a DeprecationWarning when this module is loaded.

**Comment by vladr11** [comment]
Thanks!

Created a PR, and left a note in it that the file should be removed after a major version increment. Might be useful to create an issue with that, if the PR gets merged.

Also mentioned in the deprecation warning that the functions should be imported from the top-level module as well.

**Comment by kws** [comment]
If for whatever reason you are using a 3rd party library that has wrong import in it, then you can do an ugly monkey-patch higher up in the calling code, e.g.:

```
try:
    import graphql_relay.connection.array_connection
    sys.modules['graphql_relay.connection.arrayconnection'] = graphql_relay.connection.array_connection
except ModuleNotFoundError:
    pass
```

Note: I don't recommend this, but it will keep the code working until the imports are fixed.

**Comment by Cito** [comment]
@kes, we love Python for its monkey-patchability.

v3.1.5 with the backward compatibility fix is now released, so this should not be needed any more.
