### ISSUE TITLE
Problem with graphql_relay.connection.arrayconnection

### ISSUE THREAD

**Issue by oliworkspace** [graphql-python/graphql-relay-py#46]
Hello.
After 3.1.1 update graphql_relay.connection.arrayconnection renamed to graphql_relay.connection.array_connection and some packages not working.
Can you add graphql_relay.connection.arrayconnection with import * for reverse compatibility?

**Comment by Cito** [comment]
Please see #44 for this issue.

**Comment by Cito** [comment]
@oliworkspace v3.1.5 with the backward compatibility fix is now released.
