### ISSUE TITLE
Unicode cursors passed to get_offset_with_default are rejected

### ISSUE THREAD

**Issue by darkenedsoul** [graphql-python/graphql-relay-py#5]
I'm unsure if this is an actual problem or intentional on graphql-relay's end but when using graphene hooked into django (1.8.6) cursor based querying returns the same result set as without. This is due to the aforementioned function (in graphql_relay.connection.arrayconnection) specifically only allowing instances of str. I monkeypatched an alternative function that casts the unicode to str and was able to get sliced results.

**Comment by syrusakbary** [comment]
This is now fixed by commit: 59a314fcf74f4d0bb6f9fe8dc445ecd0307752c8

You can use the latest version now: `0.4.2` :)
